update i-Haklab at v3.5.1

diff --git a/packages/kalilinux/kalilinux-installer b/packages/kalilinux/kalilinux-installer
--- a/packages/kalilinux/kalilinux-installer
+++ b/packages/kalilinux/kalilinux-installer
@@ -3,9 +3,22 @@ IFS=$'\n\t'
 
 wget --tries=20 --quiet \
 	https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Kali/kali-xfce.sh \
-	-O kali-xfce.sh
-chmod +x kali-xfce.sh
-bash kali-xfce.sh
-echo "deb [trusted=yes] http://http.kali.org/kali kali-rolling main contrib non-free" > ${HOME}/kali-fs/etc/apt/sources.list
+	-O ${HOME}/kali-xfce.sh
+
+[[ -e ${HOME}/kali-xfce.sh ]] && {
+	chmod 777 ${HOME}/kali-xfce.sh;
+	cd;bash ${HOME}/kali-xfce.sh;
+} || {
+	echo -en "\e[31mE:\e[0m Kalilinux server not found\n";
+	exit 1
+}
+
+[[ -d ${HOME}/kali-fs/etc/apt ]] && {
+	echo "deb [trusted=yes] http://http.kali.org/kali kali-rolling main contrib non-free" > ${HOME}/kali-fs/etc/apt/sources.list
+} || {
+	echo -en "\e[31mE:\e[0m Sources files not found\n";
+	exit 1
+}
+
 exit 0
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
