update termux-docker-qemu at 0.4.0

diff --git a/packages/termux-docker-qemu/termux-docker-qemu b/packages/termux-docker-qemu/termux-docker-qemu
--- a/packages/termux-docker-qemu/termux-docker-qemu
+++ b/packages/termux-docker-qemu/termux-docker-qemu
@@ -6,32 +6,42 @@ G="\e[32m"
 Y="\e[33m"
 B="\e[34m"
 os="$1"
-mRAM="12288"
+mRAM="mRAM"
 
-[[ $# -eq 0 ]] && { echo -en "\e[33mUsage:\e[0m $0 <operative system name> x11[for a grafical enviroment]";exit;}
+[[ $# -eq 0 ]] && { 
+  echo -en "\e[33mUsage:\e[0m termux-docker-qemu <operative system name> x11[for a grafical enviroment]"
+  exit 1
+}
+
 [[ $2 == 'x11' ]] 2>/dev/null || { XorCLi="-nographic";}
+
 [[ -d ${HOME}/.local/share/termux-docker-qemu/$os ]] && {
   cd ${HOME}/.local/share/termux-docker-qemu/$os
-  case "$os" in
-    alpine|kalilinux)
-      #$(free --mega|grep "Mem"|awk '{print $2}') -smp \
-      ip=$(ifconfig 2>/dev/null|grep -oE '([0-9]{1,3}\.){3}'|grep -v 255|grep -v 127|tail -n 1)
-      qemu-system-x86_64 -machine q35 -m $mRAM
-        cpus=$(nproc) -cpu qemu64 -vga virtio -full-screen -usb \
-        -drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
-        -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \
-        -device virtio-net,netdev=n1 \
+} || {
+  echo -en $R"E:$W $(basename $0) PATH missing ...$Y Aborting.$W"
+  exit 2
+} 
+
+case "$os" in
+  alpine|kalilinux)
+    #$(free --mega|grep "Mem"|awk '{print $2}') -smp \
+    ip=$(ifconfig 2>/dev/null|grep -oE '([0-9]{1,3}\.){3}'|grep -v 255|grep -v 127|tail -n 1)
+    qemu-system-x86_64 -machine q35 -m $mRAM -smp \
+      cpus=$(nproc) -cpu qemu64 -vga virtio -full-screen -usb \
+      -drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
+      -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \
+      $XorCLi $os.img
 #        -netdev user,id=n1,net=$ip.0/24,dhcpstart=$ip.9,smb=mnt,smbserver=$ip.9,hostfwd=tcp::2222-:22 \
-        $XorCLi $os.img
-      ;;
-#    kakalilinux)
+    ;;
+  kakalilinux)
+    echo "W: kalilinux is unavailable, use it into a docker container with Alpine OS."
 #      qemu-system-x86_64 -machine q35 -m 1024 -smp cpus=4 -cpu qemu64 \ 
 #        -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \ 
 #        -hda ./$os.img -usb $XorCLi
-#      ;;
-  esac
-} || {
-  echo -en $R"E:$W $(basename $0) PATH missing ...$Y Aborting.$W"
-  exit 1
-}
+    ;;
+  *)
+    echo "E: Invalid Operative System.. Aborting."
+    exit 3
+    ;;
+esac
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
