debs added

diff --git a/packages/saycheese/preinst b/packages/saycheese/preinst
--- a/packages/saycheese/preinst
+++ b/packages/saycheese/preinst
@@ -3,11 +3,15 @@ if [[ $(id -u) -eq 0 ]]
 then
   echo -en "\e[31mE:\e[0m You need to be a common user\n"
   exit 1
+elif [[ ! -e $(command -v ngrok) ]] 2>/dev/null
+then
+	echo -en "\e[31mE:\e[0m Ngrok needed ...\e[33m Aborting.\e[0m\n"
+	exit 1
 else
   echo "Preparing enviroment ..."
-  if [[ -d ${PREFIX}/share/routersploit ]]
+  if [[ -d ${PREFIX}/share/saycheese ]]
   then
-    rm -rf ${PREFIX}/share/routersploit
+    rm -rf ${PREFIX}/share/saycheese
 	else
 		mkdir -p ${HOME}/.local/share 2>/dev/null
   fi
