update hydra-gtk

diff --git a/packages/hydra-gtk/postinst b/packages/hydra-gtk/postinst
--- a/packages/hydra-gtk/postinst
+++ b/packages/hydra-gtk/postinst
@@ -1,5 +1,6 @@
 #!/data/data/com.termux/files/usr/bin/bash
 IFS=$'\n\t'
+export PKG_CONFIG_PATH=${PREFIX}/lib
 echo "Cloning repository ..."
 git clone --quiet https://github.com/vanhauser-thc/thc-hydra ${HOME}/.local/share/hydra
 [[ -d ${HOME}/.local/share/hydra ]] && {
@@ -19,10 +20,15 @@ git clone --quiet https://github.com/vanhauser-thc/thc-hydra ${HOME}/.local/shar
     [[ -e ${HOME}/.local/share/hydra/$i ]] && {
       chmod +x ${HOME}/.local/share/hydra/$i;
       cp ${HOME}/.local/share/hydra/$i ${PREFIX}/bin/;
-    } || {
+    } && [[ -e ${PREFIX}/bin/$i ]] || {
       echo -en "\e[31mE:\e[0m $i cannot be compiled.\n";
     }
   done
+  [[ -e ${PREFIX}/lib/libXfixes.so ]] && {
+    ln -s ${PREFIX}/lib/libXfixes.so ${PREFIX}/lib/libXfixes.so.3
+  } || {
+    echo -en "\e[31mE:\e[0m libXfixes missing.\n";
+  }
   chmod 750 /data/data/com.termux/files/usr/bin/fixer
   echo "[*] hydra and xhydra installation finished."
 } || {
