update debs

diff --git a/packages/hydra-gtk/postinst b/packages/hydra-gtk/postinst
--- a/packages/hydra-gtk/postinst
+++ b/packages/hydra-gtk/postinst
@@ -1,9 +1,37 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/hydra-installer
-rm -rf ${PREFIX}/bin/hydra-installer
-wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
-chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] hydra and xhydra installation finished."
+IFS=$'\n\t'
+echo "Cloning repository ..."
+git clone --quiet https://github.com/vanhauser-thc/thc-hydra ${HOME}/.local/share/hydra
+[[ -d ${HOME}/.local/share/hydra ]] && {
+  echo "Compiling hydra and xhydra ...";
+  chmod 751 -R ${HOME}/.local/share/hydra;
+  sed -i 's|wait3(NULL, WNOHANG, NULL);|wait4(NULL, WNOHANG, NULL, NULL);|g' \
+    ${HOME}/.local/share/hydra/hydra.c;
+  cd ${HOME}/.local/share/hydra;
+  make clean;
+  sh configure --prefix=$PREFIX;
+  make;
+  make install;
+  cd hydra-gtk;
+  sh make_xhydra.sh;
+  for i in hydra xhydra
+  do
+    [[ -e ${HOME}/.local/share/hydra/$i ]] && {
+      chmod +x ${HOME}/.local/share/hydra/$i;
+      cp ${HOME}/.local/share/hydra/$i ${PREFIX}/bin/;
+    } || {
+      echo -en "\e[31mE:\e[0m $i cannot be compiled.\n";
+    }
+  done
+  chmod 750 /data/data/com.termux/files/usr/bin/fixer
+  echo "[*] hydra and xhydra installation finished."
+} || {
+  echo -en "\e[31mE:\e[0m hydra directory missing ... \e[33mAborting.\e[0m\n";
+}
+
+wget --tries=20 --quiet \
+  https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer \
+  -O /data/data/com.termux/files/usr/bin/fixer
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
