update sherlock

diff --git a/packages/sherlock/postinst b/packages/sherlock/postinst
--- a/packages/sherlock/postinst
+++ b/packages/sherlock/postinst
@@ -1,14 +1,32 @@
 #!/data/data/com.termux/files/usr/bin/bash
 IFS=$'\n\t'
 
-echo "Installing requirements (It could take a while) ..."
+chmod +x ${PREFIX}/bin/sherlock-installer
 bash ${PREFIX}/bin/sherlock-installer
+python -m pipx --no-cache-dir install sherlock-project;
 
-wget --tries=5 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
-chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] Sherlock installation finished."
-echo "[*] Run 'sherlock' to execute it."
-echo "[*] Run 'fixer' to fix any posible issue."
-echo "[!] For help going to https://t.me/Ivam3_Bot."
-echo "[*] @Ivam3: thank you for use my package."
+[[ $(command -v sherlock >/dev/null; echo $?) -eq 0 ]] && {
+    echo "[✔] sherlock installation finished."
+    echo "[➡] Run 'sherlock' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m sherlock installation fail ... \e[33mAborting.\e[0m\n";
+}
+
+# ==============================
+# INSTALLING SCRIPT FIXER
+# ==============================
+echo "[*] Installing script fixer..."
+fixerURL="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer"
+if curl -fsSL "$fixerURL" -o /data/data/com.termux/files/usr/bin/fixer; then
+    chmod 750 /data/data/com.termux/files/usr/bin/fixer
+    echo "[➡] Run 'fixer' to fix any posible issue."
+else
+    echo "[!] Error downloading fixer."
+fi
+
+# ==============================
+# FINALS MESSAGES
+# ==============================
+echo "[📢] Help: going to https://t.me/Ivam3_Bot."
+echo "[💡] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
