update sherlock

diff --git a/packages/sherlock/preinst b/packages/sherlock/preinst
--- a/packages/sherlock/preinst
+++ b/packages/sherlock/preinst
@@ -1,15 +1,12 @@
 #!/data/data/com.termux/files/usr/bin/bash
-if [[ $(id -u) -eq 0 ]]
-then
+
+if [[ $(id -u) -eq 0 ]]; then
   echo -en "\e[31mE:\e[0m You need to be a common user\n"
   exit 1
 else
-  echo "Preparing enviroment ..."
-  if [[ -d ${HOME}/.local/share/sherlock ]]
-  then
-		rm -rf ${HOME}/.local/share/sherlock
-  else
-    mkdir -p ${HOME}/.local/share 2>/dev/null
-  fi
+    [[ -e ${PREFIX}/etc/apt/sources.list.d/tur.list ]] || {
+        echo -en "\e[31mE:\e[0m Packages tur-repo required, please install it\n\trun: 'apt install tur-repo'\n\tthen reinstall sherlock\n"
+        exit 2
+    }
 fi
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
