fix E:deprecated dependence

diff --git a/packages/recon-ng/postinst b/packages/recon-ng/postinst
--- a/packages/recon-ng/postinst
+++ b/packages/recon-ng/postinst
@@ -1,9 +1,38 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/recon-ng-installer
-rm -rf ${PREFIX}/bin/recon-ng-installer
-wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
-chmod 751 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] recon-ng installation finished."
-echo "[!] For help going to https://t.me/Ivam3_Bot."
-echo "[*] @Ivam3: thank you for use my package."
+IFS=$'\n\t'
+
+echo "Cloning repository ..."
+git clone --quiet https://github.com/lanmaster53/recon-ng ${HOME}/.local/share/recon-ng
+
+[[ -d ${HOME}/.local/share/recon-ng ]] && {
+    echo "Installing requirements ...";
+    chmod 751 -R ${HOME}/.local/share/recon-ng;
+    cd ${HOME}/.local/share/recon-ng;
+	echo -n "shodan\njsonrpclib\nslowaes\nolefile\nPyPDF2\nunicodecsv" >> REQUIREMENTS;
+	python -m pip --no-color --quiet --no-cache-dir install -r REQUIREMENTS;
+    echo "[✔] recon-ng installation finished."
+    echo "[➡] Run 'recon-ng' to execute it."
+} || {
+    echo -en "\e[31mE:\e[0m recon-ng directory missing ... \e[33mAborting.\e[0m\n";
+}
+
+# ==============================
+# INSTALLING SCRIPT FIXER
+# ==============================
+echo "[*] Installing script fixer..."
+
+fixerURL="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer"
+
+if wget --quiet "$fixerURL" -O /data/data/com.termux/files/usr/bin/fixer; then
+    chmod 750 /data/data/com.termux/files/usr/bin/fixer
+    echo "[➡] Run 'fixer' to fix any posible issue."
+else
+    echo "[!] Error downloading fixer."
+fi
+
+# ==============================
+# FINALS MESSAGES
+# ==============================
+echo "[📢] Help: going to https://t.me/Ivam3_Bot."
+echo "[💡] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
