add ghunt tool

diff --git a/packages/ghunt/postinst b/packages/ghunt/postinst
--- a/packages/ghunt/postinst
+++ b/packages/ghunt/postinst
@@ -1,15 +1,16 @@
 #!/data/data/com.termux/files/usr/bin/bash
 IFS=$'\n\t'
 
-chmod +x ${PREFIX}/bin/sherlock-installer
-bash ${PREFIX}/bin/sherlock-installer
-python -m pipx --no-cache-dir install sherlock-project;
+chmod +x ${PREFIX}/bin/ghunt-installer
+bash ${PREFIX}/bin/ghunt-installer
+python -m pipx ensurepath
+python -m pipx --no-cache-dir install ghunt;
 
-[[ $(command -v sherlock >/dev/null; echo $?) -eq 0 ]] && {
-    echo "[✔] sherlock installation finished."
-    echo "[➡] Run 'sherlock' to execute it."
+[[ $(command -v ghunt >/dev/null; echo $?) -eq 0 ]] && {
+    echo "[✔] ghunt installation finished."
+    echo "[➡] Run 'ghunt' to execute it."
 } || {
-  echo -en "\e[31mE:\e[0m sherlock installation fail ... \e[33mAborting.\e[0m\n";
+  echo -en "\e[31mE:\e[0m ghunt installation fail ... \e[33mAborting.\e[0m\n";
 }
 
 # ==============================
