update ghidra & fix E: which (i-Haklab)

diff --git a/packages/ghidra/postinst b/packages/ghidra/postinst
--- a/packages/ghidra/postinst
+++ b/packages/ghidra/postinst
@@ -1,9 +1,31 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/ghidra-installer
-rm -rf ${PREFIX}/bin/ghidra-installer
-wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
+IFS=$'\n\t'
+v="10.2.3"
+d="20230208"
+echo "Downloading ghidra ..."
+wget --tries=20 --quiet \
+  https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_${v}_build/ghidra_${v}_PUBLIC_${d}.zip \
+  -O ${TMPDIR}/ghidra.zip
+if [[ -e ${TMPDIR}/ghidra.zip ]]; then
+	echo "Unpacking ghidra source code (It could take a while) ..."
+	unzip -q ${TMPDIR}/ghidra.zip -d ${HOME}/.local/share
+  mv ${HOME}/.local/share/ghidra_${v}_PUBLIC/ ${HOME}/.local/share/ghidra
+	chmod 751 -R ${HOME}/.local/share/ghidra
+  echo "Building Ghidra ..."
+  export JAVA_HOME=${PREFIX}/opt/openjdk
+  export LLVM_HOME=${PREFIX}/lib/cmake/llvm/
+  export LD_LIBRARY_PATH=$LLVM_HOME:$LD_LIBRARY_PATH
+  cd ${HOME}/.local/share/ghidra/support && ./buildNatives
+fi
+[[ -e ${HOME}/.local/share/ghidra/ghidraRun ]] && {
+  echo "[*] ghidra installation finished."
+  echo "[*] Run 'ghidra' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m ghidra directory missing ... \e[33mAborting.\e[0m\n"
+}
+wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O ${PREFIX}/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] ghidra installation finished."
+echo "[*] Run 'fixer' to fix any posible issue."
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
