update kerbrute qemu dnsenum

diff --git a/packages/dnsenum/postinst b/packages/dnsenum/postinst
--- a/packages/dnsenum/postinst
+++ b/packages/dnsenum/postinst
@@ -1,10 +1,22 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/dnsenum-installer
-rm -rf ${PREFIX}/bin/dnsenum-installer
+IFS=$'\n\t'
+echo "Cloning repository ..."
+git clone --quiet https://github.com/fwaeytens/dnsenum ${HOME}/.local/share/dnsenum
+[[ -d ${HOME}/.local/share/dnsenum ]] && {
+  echo "Installing requirements ...";
+  [[ -d ${HOME}/.dnsenum ]] || mkdir ${HOME}/.dnsenum;
+  chmod 751 -R ${HOME}/.local/share/dnsenum;
+  for dep in WWW::Mechanize Net::IP Net::DNS Net::Netmask XML::Writer String::Random
+  do
+    cpan -i $dep
+  done;
+  echo "[*] dnsenum installation finished."
+  echo "[*] Run 'dnsenum' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m dnsenum directory missing ... \e[33mAborting.\e[0m\n";
+}
 wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] dnsenum installation finished."
-echo "[*] Run 'dnsenum' to execute it."
 echo "[*] Run 'fixer' to fix any posible issue."
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
diff --git a/packages/kerbrute/postinst b/packages/kerbrute/postinst
--- a/packages/kerbrute/postinst
+++ b/packages/kerbrute/postinst
@@ -1,9 +1,21 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/kerbrute-installer
-rm -rf ${PREFIX}/bin/kerbrute-installer
+IFS=$'\n\t'
+echo "Cloning repository ..."
+git clone --quiet https://github.com/TarlogicSecurity/kerbrute ${HOME}/.local/share/kerbrute
+[[ -d ${HOME}/.local/share/kerbrute ]] && {
+  echo "Installing requirements ...";
+  chmod 751 -R ${HOME}/.local/share/kerbrute;
+  cd ${HOME}/.local/share/kerbrute;
+  python -m pip --no-color --quiet --no-cache-dir install -r requirements.txt;
+  echo "[*] kerbrute installation finished."
+  echo "[*] Run 'kerbrute' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m kerbrute directory missing ... \e[33mAborting.\e[0m\n";
+  exit 1;
+}
 wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] kerbrute installation finished."
+echo "[*] Run 'fixer' to fix any posible issue."
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
