create deb to install openjdk-21 from releases

diff --git a/packages/openjdk-21/preinstall/postinst b/packages/openjdk-21/preinstall/postinst
--- a/packages/openjdk-21/preinstall/postinst
+++ b/packages/openjdk-21/preinstall/postinst
@@ -1,9 +1,25 @@
 #!/data/data/com.termux/files/usr/bin/bash
 IFS=$'\n\t'
-wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
+javav="21.0.1-1"
+releasesLink="https://github.com/ivam3/termux-packages/releases/download"
+
+wget --quiet $releasesLink/openJDK/openjdk-21_$javav_aarch64.deb \
+    -O ${TMPDIR}/openjdk-21_$javav_aarch64.deb
+
+[[ -e ${TMPDIR}/openjdk-21_$javav_aarch64.deb  ]] || { 
+    echo "[!] Error downloading the package."; 
+    exit 1; 
+}
+
+dpkg -i ${TMPDIR}/openjdk-21_$javav_aarch64.deb
+
+wget --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer \
+    -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
+
+echo "[*] Java installed successfully."
+echo "[*] Run 'java' to execute it."
 echo "[*] Run 'fixer' to fix any posible issue."
-echo -en "[W] WARNING!!\n ╰───────➤ Run 'openjdk-21-preinst' to install java binaries files.\n"
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
