debs added

diff --git a/packages/burpsuite/burpsuite b/packages/burpsuite/burpsuite
--- a/packages/burpsuite/burpsuite
+++ b/packages/burpsuite/burpsuite
@@ -8,7 +8,7 @@ B="\e[34m"
 if [[ -e ${HOME}/.local/share/burpsuite.jar ]]
 then
 	[[ $(uname -m) = "aarch64" ]] || { printf >&2 $R"(➤_)$W Incompatible architecture";exit;}
-	[[ $(file $TMPDIR/*|grep -o "socket") >/dev/null ]] || { printf >&2 "$R(_➤)\$W Termux:Way     land server isn't running...$R aborting.$W";exit;}
+	[[ $(file $TMPDIR/*|grep -o "socket") >/dev/null ]] || { printf >&2 "$R(➤_)\$W Termux:Wayland server isn't running...$R aborting.$W";exit;}
 	export DISPLAY=:0
 	umask 000
 	exec $(command -v java) --add-opens=java.desktop/javax.swing=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED -jar ${HOME}/.local/share/burpsuite.jar
diff --git a/packages/dex2jar/dex2jar b/packages/dex2jar/dex2jar
--- a/packages/dex2jar/dex2jar
+++ b/packages/dex2jar/dex2jar
@@ -10,20 +10,16 @@ G="\e[32m"
 Y="\e[33m"
 B="\e[34m"
 
-ctrl_c(){
-	printf "\n$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n"
-	exit 0
-}
+ctrl_c(){ printf "\n$Y\n   (¿) Need a help (?)$B\nTelegram : t.me/Ivam3_Bot$W\n";exit 0;}
 
-if [[ ! -e ${PREFIX}/share/dex2jar ]]
-then
-	echo -en "$R(_➤)$W dex2jar is not installed..$Y Aborting.$W"
-	exit 0
-fi
+[[ -e ${HOME}/.local/share/dex2jar ]] || {
+	echo -en "$R(➤_)$W dex2jar is not installed..$Y Aborting.$W";
+	exit 0;
+}
 
 file=$(mktemp)
 echo "AVAILABLE TOOLS" > $file
-echo "$(ls ${PREFIX}/share/dex2jar/*.sh|cut -d "/" -f10|cut -d "." -f1)" >> $file
+echo "$(ls ${HOME}/.local/share/dex2jar/*.sh|cut -d "/" -f10|cut -d "." -f1)" >> $file
 
 usage(){
 	printf "$Y(_>)_usage :─➤$W dex2jar <tool> <options + arguments>\n$Y ╰──➤$W Example : dex2jar d2j-dex2jar -f ~/path/to/apk_to_decompile.apk$G\n"
@@ -31,13 +27,12 @@ usage(){
 	rm $file 2>/dev/null;printf "$W\n";exit 0
 }
 
-
 tool=$(grep $1 $file)
 if [[ $# -eq 0 ]] || [[ -z $tool ]] 2>/dev/null
 then
 	usage
 else
-	bash $(ls ${PREFIX}/share/dex2jar/$tool.sh) ${@:2}
+	bash $(ls ${HOME}/.local/share/dex2jar/$tool.sh) ${@:2}
 	rm $file 2>/dev/null
 fi
 
