update binwalk

diff --git a/packages/binwalk/binwalk-installer b/packages/binwalk/binwalk-installer
--- a/packages/binwalk/binwalk-installer
+++ b/packages/binwalk/binwalk-installer
@@ -1,9 +1,16 @@
 #!/data/data/com.termux/files/usr/bin/bash
 echo "Cloning repository ..."
-git clone --quiet https://github.com/ReFirmLabs/binwalk ${HOME}/.local/share/binwalk
+git clone --quiet https://github.com/ReFirmLabs/binwalk ${HOME}/.local/share/binwalk && cd $_
 chmod 750 -R ${HOME}/.local/share/binwalk
 echo "Installing requirements ..."
-cd ${HOME}/.local/share/binwalk
-python setup.py install
+cargo build --release
+[[ -e ${HOME}/.local/share/binwalk/target/release/binwalk ]] && {
+    ln -s ${HOME}/.local/share/binwalk/target/release/binwalk ${PREFIX}/bin/binwalk
+    echo "[*] Binwalk installation finished."
+    echo "[*] Run it executing 'binwalk'."
+} || {
+    echo -en "\e[31mE:\e[0m Failed to build binwalk\n"
+    exit 1
+}
 exit 0
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
