fix E:preinst termux-desktop-xfce

diff --git a/packages/termux-desktop-xfce/preinst b/packages/termux-desktop-xfce/preinst
--- a/packages/termux-desktop-xfce/preinst
+++ b/packages/termux-desktop-xfce/preinst
@@ -4,12 +4,17 @@ then
   echo -en "\e[31mE:\e[0m You need to be a common user\n"
   exit 1
 else
-  echo "Preparing enviroment ..."
-  yes|termux-setup-storage
-  [[ -d ${HOME}/Desktop ]] || { mkdir -p ${HOME}/Desktop;}
+  
+    stderr=$(ls ${PREFIX}/etc/apt/sources.list.d/x11.list &>/dev/null ; echo $?) 
+  
+    [[ $stderr -eq 0 ]] || {
+        echo "! x11-repo repository is required, please install it running ... 'apt install x11-repo'"
+        exit 1
+    }
 
-  ! apt search x11-repo 2>/dev/null | grep -o "installed" >/dev/null && {
-    echo "! x11-repo repository is required, please install it running ... 'apt install x11-repo'"
-  }
+    echo -en "\rPreparing enviroment ..."
+    # yes|termux-setup-storage
+    [[ -d ${HOME}/Desktop ]] || { mkdir -p ${HOME}/Desktop;}
+    echo -en "DONE.\n"
 fi
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
