clean code

diff --git a/packages/redhawk/postinst b/packages/redhawk/postinst
--- a/packages/redhawk/postinst
+++ b/packages/redhawk/postinst
@@ -1,10 +1,20 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/redhawk-installer
-rm -rf ${PREFIX}/bin/redhawk-installer
+IFS=$'\n\t'
+echo "Cloning repository ..."
+git clone --quiet https://github.com/Tuhinshubhra/RED_HAWK ${HOME}/.local/share/redhawk
+[[ -d ${HOME}/.local/share/redhawk ]] && {
+    echo "Installing requirements ...";
+    chmod 751 -R ${HOME}/.local/share/redhawk;
+    echo "[*] redhawk installation finished."
+    echo "[*] Run 'redhawk' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m redhawk directory missing ... \e[33mAborting.\e[0m\n";
+  exit 1;
+}
+
 wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] redhawk installation finished."
-echo "[*] Run 'redhawk' to execute it."
+
 echo "[*] Run 'fixer' to fix any posible issue."
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
