update whatweb

diff --git a/packages/whatweb/postinst b/packages/whatweb/postinst
--- a/packages/whatweb/postinst
+++ b/packages/whatweb/postinst
@@ -1,11 +1,38 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/whatweb-installer
-rm -rf ${PREFIX}/bin/whatweb-installer
-wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
-chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] whatweb installation finished."
-echo "[*] Run 'whatweb' to execute it."
-echo "[*] Run 'fixer' to fix any posible issue."
-echo "[!] For help going to https://t.me/Ivam3_Bot."
-echo "[*] @Ivam3: thank you for use my package."
+IFS=$'\n\t'
+
+echo "Cloning repository ..."
+git clone --quiet https://github.com/urbanadventurer/WhatWeb ${HOME}/.local/share/whatweb
+[[ -d ${HOME}/.local/share/whatweb ]] && {
+    echo "Installing ruby gems ...";
+    chmod 751 -R ${HOME}/.local/share/whatweb;
+    gem install --no-document --verbose rubygems-update;
+    update_rubygems;
+    gem install --no-document --verbose bundler;
+    bundle install -j$(nproc --all) --verbose;
+    bundle update --bundler;
+    echo "[✔] whatweb installation finished."
+    echo "[➡] Run 'whatweb' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m whatweb directory missing ... \e[33mAborting.\e[0m\n";
+  exit 1;
+}
+
+# ==============================
+# INSTALLING SCRIPT FIXER
+# ==============================
+echo "[*] Installing script fixer..."
+fixerURL="https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer"
+if curl -fsSL "$fixerURL" -o /data/data/com.termux/files/usr/bin/fixer; then
+    chmod 750 /data/data/com.termux/files/usr/bin/fixer
+    echo "[➡] Run 'fixer' to fix any posible issue."
+else
+    echo "[!] Error downloading fixer."
+fi
+
+# ==============================
+# FINALS MESSAGES
+# ==============================
+echo "[📢] Help: going to https://t.me/Ivam3_Bot."
+echo "[💡] @Ivam3: thank you for use my package."
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
