clean code of cryptovenom

diff --git a/packages/cryptovenom/postinst b/packages/cryptovenom/postinst
--- a/packages/cryptovenom/postinst
+++ b/packages/cryptovenom/postinst
@@ -1,9 +1,27 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/cryptovenom-installer
-rm -rf ${PREFIX}/bin/cryptovenom-installer
+IFS=$'\n\t'
+
+git clone --quiet --depth 1 https://github.com/lockedbyte/cryptovenom \
+    ${HOME}/.local/share/cryptovenom && cd $_
+
+[[ -d ${HOME}/.local/share/cryptovenom ]] && { 
+    echo "Installing requirements ...";
+    chmod 751 -R ${HOME}/.local/share/cryptovenom;
+    cp aux/cryptovenom.py . ;
+    chmod +x cryptovenom.py;
+    python -m pip --no-color --quiet --no-cache-dir install -r requirements.txt;
+    echo "[*] cryptovenom installation finished."
+    echo "[*] Run 'cryptovenom' to execute it."
+} || {
+  echo -en "\e[31mE:\e[0m cryptovenom directory missing ... \e[33mAborting.\e[0m\n";
+  exit 1;
+}
+
 wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
-echo "[*] cryptovenom installation finished."
+
+echo "[*] Run 'fixer' to fix any posible issue."
 echo "[!] For help going to https://t.me/Ivam3_Bot."
 echo "[*] @Ivam3: thank you for use my package."
+
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
