update fake-sms at v2

diff --git a/packages/fake-sms/postinst b/packages/fake-sms/postinst
--- a/packages/fake-sms/postinst
+++ b/packages/fake-sms/postinst
@@ -1,7 +1,20 @@
 #!/data/data/com.termux/files/usr/bin/bash
-bash ${PREFIX}/bin/fake-sms-installer
-rm -rf ${PREFIX}/bin/fake-sms-installer
-wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
+IFS=$'\n\t'
+echo "Cloning repository ..."
+git clone --quiet https://github.com/machine1337/fake-sms ${HOME}/.local/share/fake-sms
+[[ -d ${HOME}/.local/share/fake-sms ]] && {
+  echo "Installing requirements ...";
+  chmod 751 -R ${HOME}/.local/share/fake-sms
+  python -m pip --no-color --quiet --no-cache-dir install --upgrade pip
+  python -m pip --no-color --quiet --no-cache-dir install -r \
+    ${HOME}/.local/share/fake-sms/requirements.txt
+} || {
+  echo -en "\e[31mE:\e[0m fake-sms directory missing ... \e[33mAborting.\e[0m\n";
+  exit 1;
+}
+wget --tries=20 --quiet \
+  https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer \
+  -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
 echo "[*] fake-sms installation finished."
 echo "[*] Run 'fake-sms' to execute it."
