maltego toolkit added & fix sayhello tool

diff --git a/packages/build-env b/packages/build-env
--- a/packages/build-env
+++ b/packages/build-env
@@ -33,7 +33,7 @@ while getopts n:v:a:d:p:s:i:h opts; do
 	esac
 done
 
-mkdir -p $pkgName
+mkdir -p $pkgName/img
 #MANIFIEST
 cat <<- CONF > $pkgName/manifiest.json
 {
@@ -42,12 +42,13 @@ cat <<- CONF > $pkgName/manifiest.json
   "arch": "$arch",
   "homepage": "https://$page",
   "maintainer": "Ivam3 <https://t.me/Ivam3_Bot>",
-  "depends": ["git, ruby"],
+  "depends": ["git"],
   "suggests": ["i-haklab"],
   "description": "",
   "files" :{
-    "$pkgName-installer": "bin/$pkgName-installer",
-    "$pkgName": "bin/$pkgName"
+    "$pkgName": "bin/$pkgName",
+    "img/$pkgName.png": "${PREFIX}/share/applications/$pkgName/img/$pkgName.png",
+    "$pkgName.desktop": "${PREFIX}/share/applications/$pkgName/$pkgName.desktop"
   }
 }
 CONF
@@ -72,22 +73,20 @@ fi
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
 CONF
 
-#INSTALLER
-cat <<- CONF > $pkgName/$pkgName-installer
-#!/data/data/com.termux/files/usr/bin/bash
-IFS=$'\\n\\t'
-echo "Cloning repository ..."
-git clone --quiet https://$page \${HOME}/.local/share/$pkgName
-[[ -d \${HOME}/.local/share/$pkgName ]] && {
-  echo "Installing requirements ...";
-  chmod 751 -R \${HOME}/.local/share/$pkgName;
-  python -m pip --no-color --quiet --no-cache-dir install -r \${HOME}/.local/share/$pkgName/requirements.txt; 
-} || {
-  echo -en "\e[31mE:\e[0m $pkgName directory missing ... \e[33mAborting.\e[0m\n";
-  exit 1;
-}
-exit 0
-####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
+#DESKTOP
+cat <<- CONF > $pkgName/$pkgName.desktop
+[Desktop Entry]
+Name=$pkgName
+GenericName=$pkgName
+Comment=
+Comment[es]=
+Version=$pkgv
+Exec=$pkgName
+Icon=/data/data/com.termux/files/usr/share/applications/$pkgName/img/$pkgName.png
+Terminal=false
+Type=Application
+Categories=System
+X-Desktop-File-Install-Version=$pkgv
 CONF
 
 #PREINST
@@ -112,8 +111,16 @@ CONF
 #POSTINST
 cat <<- CONF > $pkgName/postinst
 #!/data/data/com.termux/files/usr/bin/bash
-bash \${PREFIX}/bin/$pkgName-installer
-rm -rf \${PREFIX}/bin/$pkgName-installer
+IFS=$'\\n\\t'
+echo "Cloning repository ..."
+git clone --quiet https://$page \${HOME}/.local/share/$pkgName
+[[ -d \${HOME}/.local/share/$pkgName ]] && {
+  echo "Installing requirements ...";
+  chmod 751 -R \${HOME}/.local/share/$pkgName;
+  python -m pip --no-color --quiet --no-cache-dir install -r \${HOME}/.local/share/$pkgName/requirements.txt; 
+} || {
+  echo -en "\e[31mE:\e[0m $pkgName directory missing ... \e[33mAborting.\e[0m\n";
+}
 wget --tries=20 --quiet https://raw.githubusercontent.com/ivam3/i-Haklab/master/.deb/home/.local/bin/fixer -O /data/data/com.termux/files/usr/bin/fixer
 chmod 750 /data/data/com.termux/files/usr/bin/fixer
 echo "[*] $pkgName installation finished."
