update i-Haklab at v3.5.2

diff --git a/packages/build-env b/packages/build-env
--- a/packages/build-env
+++ b/packages/build-env
@@ -61,11 +61,10 @@ R="\\e[31m"
 G="\\e[32m"
 Y="\\e[33m"
 B="\\e[34m"
-if [[ -d \${HOME}/.local/share/\$(basename \$0) ]]
+if [[ -d \${HOME}/.local/share/$pkgName ]]
 then
-  pushd \${HOME}/.local/share/\$(basename \$0) >/dev/null
-  \$(command -v ruby) \$(basename \$0).rb \${@:1}
-	popd
+  cd \${HOME}/.local/share/\$(basename \$0) >/dev/null
+  \$(command -v python) \$(basename \$0).py \${@:1}
 else
   echo -en \$R"E:\$W \$(basename \$0) PATH missing ...\$Y Aborting.\$W"
   exit 1
@@ -77,7 +76,17 @@ CONF
 cat <<- CONF > $pkgName/$pkgName-installer
 #!/data/data/com.termux/files/usr/bin/bash
 IFS=$'\\n\\t'
+echo "Cloning repository ..."
+git clone --quiet https... \${HOME}/.local/share/$pkgName
+[[ -d \${HOME}/.local/share/$pkgName ]] && {
+  echo "Installing requirements ...";
+  chmod 751 -R \${HOME}/.local/share/$pkgName;
+  cd \${HOME}/.local/share/$pkgName;
 
+} || {
+  echo -en "\e[31mE:\e[0m $pkgName directory missing ... \e[33mAborting.\e[0m\n";
+  exit 1;
+}
 exit 0
 ####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
 CONF
